version: 0.15-1

mqtt:
  enabled: false

detectors:
  coral:
    type: edgetpu
    device: pci

detect:
  fps: 5  # Global detection FPS
  enabled: true

objects:
  track:
    - person
    - car
  filters:
    person:
      min_area: 5000     # Tweak as needed
      max_area: 100000
      threshold: 0.7
    car:
      min_area: 10000
      max_area: 250000
      threshold: 0.7

cameras:
  cam_front_pano:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_REOLINK_PASSWORD}@192.168.50.70:554//h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://admin:{FRIGATE_REOLINK_PASSWORD}@192.168.50.70:554//h264Preview_01_main
          roles:
            - record

  cam_front_porch:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_REOLINK_PASSWORD}@192.168.50.123:554//h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://admin:{FRIGATE_REOLINK_PASSWORD}@192.168.50.123:554//h264Preview_01_main
          roles:
            - record

  cam_north_entrance:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_REOLINK_PASSWORD}@192.168.50.124:554//h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://admin:{FRIGATE_REOLINK_PASSWORD}@192.168.50.124:554//h264Preview_01_main
          roles:
            - record

  cam_south_entrance:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_REOLINK_PASSWORD}@192.168.50.156:554//h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://admin:{FRIGATE_REOLINK_PASSWORD}@192.168.50.156:554//h264Preview_01_main
          roles:
            - record

  cam_driveway:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_REOLINK_PASSWORD}@192.168.50.251:554//h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://admin:{FRIGATE_REOLINK_PASSWORD}@192.168.50.251:554//h264Preview_01_main
          roles:
            - record

  # Hikvision Rear Pano
  cam_rear_pano:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_HIKVISION_PASSWORD}@192.168.50.250:554/Streaming/Channels/101/
          roles:
            - record
        - path: rtsp://admin:{FRIGATE_HIKVISION_PASSWORD}@192.168.50.250:554/Streaming/Channels/102/
          roles:
            - detect
