mqtt:
  enabled: false

detectors:
  coral:
    type: edgetpu
    device: pci

#snapshots:
#  enabled: true
#  bounding_box: true

cameras:
  cam_pano_1:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_REOLINK_PASSWORD}@192.168.50.68:554//h264Preview_01_sub
          roles:
            - record
            - detect
    detect:
      enabled: true
    objects:
      track:
        - person
        - car
version: 0.15-1
