---
repos:
  # 1) Housekeeping and basic sanity checks
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-merge-conflict
          - id: check-yaml
          - id: check-toml

  # 2) Formatters
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.6.4
      hooks:
          - id: ruff-format
          - id: ruff
            args: [--fix, --exit-non-zero-on-fix]

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.1
      hooks:
          - id: yamlfmt

    - repo: https://github.com/scop/pre-commit-shfmt
      rev: v3.7.0-1
      hooks:
          - id: shfmt
            args: [-w, -i, '2', -ci]

  # 3) Linters and security
    - repo: https://github.com/shellcheck-py/shellcheck-py
      rev: v0.10.0.1
      hooks:
          - id: shellcheck
            args: [-x]

    - repo: https://github.com/PyCQA/bandit
      rev: 1.7.9
      hooks:
          - id: bandit
            args: [-c, pyproject.toml, -r, .]

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.11.2
      hooks:
          - id: mypy
            args: [--python-version=3.13]
