services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    shm_size: "64mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config.yml:/config/config.yml
    environment:
      - FRIGATE_RTSP_PASSWORD=your_password
    ports:
      - "5000:5000"
      - "1935:1935"
    image: ghcr.io/blakeblackshear/frigate:stable
