---
services:
    mqtt:
        image: eclipse-mosquitto:2.0
        container_name: mqtt
        restart: unless-stopped
        ports:
            - 1883:1883 # MQTT
            - 9001:9001 # WebSockets (optional)
        volumes:
            - ./mosquitto/config:/mosquitto/config
            - ./mosquitto/data:/mosquitto/data
            - ./mosquitto/log:/mosquitto/log
        networks:
            - frigate_net

#  homeassistant:
#    image: ghcr.io/home-assistant/home-assistant:stable
#    container_name: homeassistant
#    restart: unless-stopped
#    environment:
#      - TZ=America/New_York
#    volumes:
#      - ./homeassistant/config:/config
#      - /etc/localtime:/etc/localtime:ro
#    ports:
#      - "8123:8123"     # HA Web UI
#    depends_on:
#      - mqtt
#    networks:
#      - frigate_net

    frigate:
        container_name: frigate
        image: ghcr.io/blakeblackshear/frigate:stable
        privileged: true
        restart: unless-stopped
        shm_size: 512mb
        devices:
            - /dev/apex_0:/dev/apex_0
        volumes:
            - ./config:/config
            - /mnt/frigate-storage:/media/frigate
            - type: tmpfs
              target: /tmp/cache
              tmpfs:
                  size: 1000000000
        ports:
            - 5000:5000
            - 8971:8971
            - 8554:8554
            - 8555:8555/tcp
            - 8555:8555/udp
        env_file:
            - .env
        depends_on:
            - mqtt
        networks:
            - frigate_net

    ml-processor:
        build: ./ml-processor
        container_name: ml-processor
        restart: unless-stopped
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]
        volumes:
            - /mnt/frigate-storage:/media/frigate:ro
            - ./ml-processor/models:/app/models
            - ./ml-processor/data:/app/data
            - ./ml-processor/logs:/app/logs
        environment:
            - MQTT_HOST=mqtt
            - MQTT_PORT=1883
            - FRIGATE_API_URL=http://frigate:5000
            - POSTGRES_URL=postgresql://myuser:mypassword@postgres-vector:5432/mydatabase
            - CUDA_VISIBLE_DEVICES=0
        depends_on:
            - mqtt
            - frigate
            - postgres-vector
        networks:
            - frigate_net

    redis:
        image: redis:7-alpine
        container_name: redis
        restart: unless-stopped
        ports:
            - 6379:6379
        volumes:
            - ./redis_data:/data
        networks:
            - frigate_net

    ollama:
        image: ollama/ollama
        container_name: ollama
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]
        volumes:
            - ./ollama_data:/root/.ollama
        ports:
            - 11434:11434
        restart: unless-stopped
        networks:
            - frigate_net

    open-webui:
        image: ghcr.io/open-webui/open-webui:main
        container_name: open-webui
        depends_on:
            - ollama
        ports:
            - 3000:8080
        environment:
            - OLLAMA_BASE_URL=http://ollama:11434
        volumes:
            - ./open-webui_data:/app/backend/data
        restart: unless-stopped
        networks:
            - frigate_net

    postgres-vector:
        image: pgvector/pgvector:pg16
        container_name: postgres-vector
        environment:
            - POSTGRES_USER=myuser
            - POSTGRES_PASSWORD=mypassword
            - POSTGRES_DB=mydatabase
        ports:
            - 5432:5432
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
        restart: unless-stopped
        networks:
            - frigate_net

networks:
    frigate_net:
        driver: bridge
